### ISSUE TITLE
giantswarm namespace is not protected

### ISSUE THREAD

**Issue by danibaeyens** [giantswarm/linkerd-control-plane-app#129]
The following situation can happen:
 - linkerd has been installed in the cluster
 - proxy-injector is not working properly
 - for a certain reason, chart-operator on giantswarm namespace gets rolled/killed/restarted
 - the mutationwebhook detects there is a new deployment on giantswarm namespace and tries to inject the pod
As the mutationwebhook has by default a Fail policy, it will fail and chart-operator would not start, leaving the cluster without the ability of receiving further apps from the management cluster.

An easy fix is by modifying the namespaceSelector which decides which namespaces are being observed or not by the proxy-injector, and add giantswarm namespace

**Comment by Gacko** [comment]
Closing this as we implemented it in one of the recent version: https://github.com/giantswarm/linkerd-control-plane-app/blob/main/helm/linkerd-control-plane/values.yaml#L362
